# Generated by Django 4.1.3 on 2022-11-26 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroAcquaintance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="entities.hero"
                    ),
                ),
            ],
        ),
    ]
