# Generated by Django 4.1.3 on 2022-11-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0002_heroacquaintance"),
    ]

    operations = [
        migrations.AddField(
            model_name="heroacquaintance",
            name="name",
            field=models.CharField(default="zon", max_length=100),
        ),
    ]
