# Generated by Django 4.1.3 on 2022-11-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0005_heroacquaintance_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroacquaintance",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
