# Generated by Django 4.1.3 on 2022-11-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_remove_hero_fathers_alter_hero_father'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='hero_headshots/'),
        ),
    ]
